import type { Metadata } from "next";
import { Kanit } from "next/font/google";
import "./globals.css";

const kanit = Kanit({
  subsets: ["thai"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
});

export const metadata: Metadata = {
  title: "Varity Calculate Web Site",
  description: "Generated by create next app",
  keywords: [
    "Varity Calculate",
    "เครื่องคำนวณ",
    "คำนวณรูปทรง",
    "คำนวนเงินแชร์",
    "คำนวณ BMI, BMR",
  ],
  authors: [{ name: "DTI-SAU Team", url: "https://dti.sau.ac.th" }],
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${kanit.className} `}>{children}</body>
    </html>
  );
}
